/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MealPlansRouteImport } from './routes/meal-plans'
import { Route as MealLibraryRouteImport } from './routes/meal-library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as IntakeFormsRouteImport } from './routes/intake-forms'
import { Route as FoodDatabaseRouteImport } from './routes/food-database'
import { Route as CmsRouteImport } from './routes/cms'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CmsIndexRouteImport } from './routes/cms.index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as CmsPagesPageIdRouteImport } from './routes/cms.pages.$pageId'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlansRoute = MealPlansRouteImport.update({
  id: '/meal-plans',
  path: '/meal-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const MealLibraryRoute = MealLibraryRouteImport.update({
  id: '/meal-library',
  path: '/meal-library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeFormsRoute = IntakeFormsRouteImport.update({
  id: '/intake-forms',
  path: '/intake-forms',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodDatabaseRoute = FoodDatabaseRouteImport.update({
  id: '/food-database',
  path: '/food-database',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsRoute = CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsIndexRoute = CmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CmsRoute,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const CmsPagesPageIdRoute = CmsPagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => CmsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/clients': typeof ClientsRouteWithChildren
  '/cms': typeof CmsRouteWithChildren
  '/food-database': typeof FoodDatabaseRoute
  '/intake-forms': typeof IntakeFormsRoute
  '/journal': typeof JournalRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/meal-library': typeof MealLibraryRoute
  '/meal-plans': typeof MealPlansRoute
  '/messages': typeof MessagesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/cms/': typeof CmsIndexRoute
  '/cms/pages/$pageId': typeof CmsPagesPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/food-database': typeof FoodDatabaseRoute
  '/intake-forms': typeof IntakeFormsRoute
  '/journal': typeof JournalRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/meal-library': typeof MealLibraryRoute
  '/meal-plans': typeof MealPlansRoute
  '/messages': typeof MessagesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients': typeof ClientsIndexRoute
  '/cms': typeof CmsIndexRoute
  '/cms/pages/$pageId': typeof CmsPagesPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/clients': typeof ClientsRouteWithChildren
  '/cms': typeof CmsRouteWithChildren
  '/food-database': typeof FoodDatabaseRoute
  '/intake-forms': typeof IntakeFormsRoute
  '/journal': typeof JournalRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/meal-library': typeof MealLibraryRoute
  '/meal-plans': typeof MealPlansRoute
  '/messages': typeof MessagesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/cms/': typeof CmsIndexRoute
  '/cms/pages/$pageId': typeof CmsPagesPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/billing'
    | '/clients'
    | '/cms'
    | '/food-database'
    | '/intake-forms'
    | '/journal'
    | '/leads'
    | '/login'
    | '/meal-library'
    | '/meal-plans'
    | '/messages'
    | '/reports'
    | '/settings'
    | '/team'
    | '/clients/$clientId'
    | '/clients/'
    | '/cms/'
    | '/cms/pages/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/billing'
    | '/food-database'
    | '/intake-forms'
    | '/journal'
    | '/leads'
    | '/login'
    | '/meal-library'
    | '/meal-plans'
    | '/messages'
    | '/reports'
    | '/settings'
    | '/team'
    | '/clients/$clientId'
    | '/clients'
    | '/cms'
    | '/cms/pages/$pageId'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/billing'
    | '/clients'
    | '/cms'
    | '/food-database'
    | '/intake-forms'
    | '/journal'
    | '/leads'
    | '/login'
    | '/meal-library'
    | '/meal-plans'
    | '/messages'
    | '/reports'
    | '/settings'
    | '/team'
    | '/clients/$clientId'
    | '/clients/'
    | '/cms/'
    | '/cms/pages/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BillingRoute: typeof BillingRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  CmsRoute: typeof CmsRouteWithChildren
  FoodDatabaseRoute: typeof FoodDatabaseRoute
  IntakeFormsRoute: typeof IntakeFormsRoute
  JournalRoute: typeof JournalRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  MealLibraryRoute: typeof MealLibraryRoute
  MealPlansRoute: typeof MealPlansRoute
  MessagesRoute: typeof MessagesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plans': {
      id: '/meal-plans'
      path: '/meal-plans'
      fullPath: '/meal-plans'
      preLoaderRoute: typeof MealPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-library': {
      id: '/meal-library'
      path: '/meal-library'
      fullPath: '/meal-library'
      preLoaderRoute: typeof MealLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake-forms': {
      id: '/intake-forms'
      path: '/intake-forms'
      fullPath: '/intake-forms'
      preLoaderRoute: typeof IntakeFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-database': {
      id: '/food-database'
      path: '/food-database'
      fullPath: '/food-database'
      preLoaderRoute: typeof FoodDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/': {
      id: '/cms/'
      path: '/'
      fullPath: '/cms/'
      preLoaderRoute: typeof CmsIndexRouteImport
      parentRoute: typeof CmsRoute
    }
    '/clients/': {
      id: '/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/cms/pages/$pageId': {
      id: '/cms/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/cms/pages/$pageId'
      preLoaderRoute: typeof CmsPagesPageIdRouteImport
      parentRoute: typeof CmsRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface CmsRouteChildren {
  CmsIndexRoute: typeof CmsIndexRoute
  CmsPagesPageIdRoute: typeof CmsPagesPageIdRoute
}

const CmsRouteChildren: CmsRouteChildren = {
  CmsIndexRoute: CmsIndexRoute,
  CmsPagesPageIdRoute: CmsPagesPageIdRoute,
}

const CmsRouteWithChildren = CmsRoute._addFileChildren(CmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  BillingRoute: BillingRoute,
  ClientsRoute: ClientsRouteWithChildren,
  CmsRoute: CmsRouteWithChildren,
  FoodDatabaseRoute: FoodDatabaseRoute,
  IntakeFormsRoute: IntakeFormsRoute,
  JournalRoute: JournalRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  MealLibraryRoute: MealLibraryRoute,
  MealPlansRoute: MealPlansRoute,
  MessagesRoute: MessagesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
